- name : Clone liquidprompt
  git:
    repo: 'https://github.com/nojhan/liquidprompt.git'
    dest: ~/config/liquidprompt
    update: no

- name : Create liquidprompt directory
  file:
    path: ~/.dotfiles/liquidprompt
    state: directory

- name : Add configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'liquidprompt.source', dest: '~/.dotfiles/liquidprompt/source.sh' }

- name : Create completion directory
  file:
    path: ~/.dotfiles/completion
    state: directory

- name : Add completion loading
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'completion.source', dest: '~/.dotfiles/completion/source.sh' }
