- name : Clone liquidprompt
  git:
    repo: 'https://github.com/nojhan/liquidprompt.git'
    dest: ~/config/liquidprompt
    update: no

- name : Create liquidprompt directory
  file:
    path: ~/.dotfiles/liquidprompt
    state: directory
