- name : Add configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'bashrc', dest: '~/.bashrc' }
    - { src: 'bash_profile', dest: '~/.bash_profile' }
    - { src: 'inputrc', dest: '~/.inputrc' }
