- name: Install emacs from homebrew cask
  homebrew_cask:
    name: emacs
    state: present

- name: Install emacs fonts from homebrew cask
  homebrew_cask:
    name: font-firacode-nerd-font-mono
    state: present

- name: Install ispell (used by emacs flyspell)
  homebrew:
    name: ispell
    state: present
