- name: Include OS-specific install tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install my emacs config
  git:
    repo: 'https://github.com/OlivierCazade/emacs.git'
    dest: ~/config/emacs
    update: no

- name: Create emacs directory symbolic link
  file:
    src: ~/config/emacs
    dest: ~/.emacs.d
    state: link
