- name: Install small cli tools
  homebrew:
    name: bash
    state: present

- name: Install iterm2 from homebrew cask
  homebrew_cask:
    name: iterm2
    state: present

- name: Install spotify from homebrew cask
  homebrew_cask:
    name: spotify
    state: present

- name: Install chrome from homebrew cask
  homebrew_cask:
    name: google-chrome
    state: present

- name: Install firefox from homebrew cask
  homebrew_cask:
    name: firefox
    state: present

- name: Install small cli tools
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - tree
    - wget
    - pstree

# TODO add karabiner config
- name: Install karabiner from homebrew cask
  homebrew_cask:
    name: karabiner-elements
    state: present
