- name: Docker dependencies installation
  apt:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
  become: true

- name: Add docker repositories
  apt_repository:
    repo: 'deb https://download.docker.com/linux/debian stretch stable'
    update_cache: "yes"
    state: "present"
  become: true

- name: Docker installation
  apt:
    name: "docker-ce"
    state: latest
  become: true

- name: Checking docker group
  group:
    name: docker
    state: present
    system: yes
  become: true

- name: Adding user to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  become: true
  with_items:
    - "{{ ansible_user }}"
    - docker

- name: Starting docker
  service:
    name: "docker"
    state: started
    enabled: yes
  become: true
